[package]
name = "va0ck/folder-net"
description = "Server/Client communication module organized & called by with folder names."
version = "0.0.4"
license = "MIT"
authors = ["Va0ck"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
[dependencies]
